# File di configurazione per i secrets
# Aggiungi le tue credenziali qui

# Google OAuth Credentials
GOOGLE_CLIENT_ID = "your_google_client_id.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "your_google_client_secret"

# OpenAI API Key
OPENAI_API_KEY = "your_openai_api_key"

# Configurazione aggiuntiva
[gsc]
redirect_uri = "http://localhost:8501"
scopes = ["https://www.googleapis.com/auth/webmasters.readonly"]
